import type { NextPage } from "next";
import Head from "next/head";
import Banner from "@components/Home/Banner";
import TrendingSection from "@components/Home/Trending-Invenstments/FindProjectSection";
import FeaturedProperty from "@components/Home/Featured-Products/FeaturedProperty";
import TopProperties from "@components/Home/TopProperties";
import InvestContent from "@components/Home/InvestContent";
import InvestorAndDeveloper from "@components/Home/InvestorAndDeveloper";
import styles from "@styles/Home.module.css";

const Home: NextPage = ({ data }: any) => {
  console.log("Data:", data);
  return (
    <>
      <Head>
        <title>Handover Digital Holdings FZCO</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className={`relative ${styles.overlay}`}>
        <div className={`relative ${styles.banner}`}>
          <Banner />
        </div>
        <div className={`relative ${styles.properties} overflow-hidden`}>
          <TopProperties properties={data.latest_properties} />
        </div>
        {/* <div className='absolute z-0'>
                    <Image src={elementImg} className='object-contain bottom-0' />
                </div> */}
      </div>

      <TrendingSection />

      <InvestorAndDeveloper />

      <InvestContent />

      {data.latest_properties != null && (
        <FeaturedProperty data={data.latest_properties} />
      )}
    </>
  );
};

export default Home;

export async function getServerSideProps(context: any) {
  // Fetch data from external API
  let latest_properties = null;
  const res = await fetch(`${process.env.API_URL}/property/sort/desc`);
  if (res.status == 200) {
    latest_properties = await res.json();
  }

  // Pass data to the page via props
  return {
    props: {
      data: {
        latest_properties,
      },
    },
  };
}
